### ISSUE TITLE
Crash when loading No-Intro roms

### ISSUE THREAD

**Issue by Kivutar** [libretro/libretro-handy#11]
I get this output:

    Invalid Cart.
    Invalid cart.
    Invalid cart.

And this backtrace:

    #0  0x00007ffff0a485f8 in raise () from /usr/lib/libc.so.6
    #1  0x00007ffff0a49a7a in abort () from /usr/lib/libc.so.6
    #2  0x00007ffff0a8705a in __libc_message () from /usr/lib/libc.so.6
    #3  0x00007ffff0a8c9a6 in malloc_printerr () from /usr/lib/libc.so.6
    #4  0x00007ffff0a8d18e in _int_free () from /usr/lib/libc.so.6
    #5  0x00007fffe1703c88 in CSystem::CSystem(char const*, char const*) () from /usr/lib/libretro/handy_libretro.so
    #6  0x00007fffe17049b6 in retro_load_game () from /usr/lib/libretro/handy_libretro.so
    #7  0x0000555555589169 in load_content (content=0x555555eff7f0, content=0x555555eff7f0, special=<optimized out>) at content.c:516
    #8  init_content_file () at content.c:671
    #9  0x0000555555580be3 in event_init_content () at command_event.c:564
    #10 event_init_core () at command_event.c:617
    #11 event_command (cmd=cmd@entry=EVENT_CMD_CORE_INIT) at command_event.c:1272
    #12 0x000055555557e011 in rarch_main_init (argc=7, argv=0x7fffffff1fe0) at retroarch.c:1237
    #13 0x000055555557b38b in main_load_content (argc=argc@entry=0, argv=argv@entry=0x0, args=args@entry=0x0, environ_get=environ_get@entry=0x5555555fa9a0 <menu_environment_get>, 
        process_args=0x0) at frontend/frontend.c:228
    #14 0x00005555555fac10 in menu_load_content (type=type@entry=CORE_TYPE_PLAIN) at menu/menu.c:108
    #15 0x000055555557d967 in rarch_ctl (state=state@entry=RARCH_CTL_LOAD_CONTENT, data=data@entry=0x0) at retroarch.c:1396
    #16 0x00005555555811e9 in event_command (cmd=cmd@entry=EVENT_CMD_LOAD_CONTENT_PERSIST) at command_event.c:950
    #17 0x00005555555811fd in event_command (cmd=cmd@entry=EVENT_CMD_LOAD_CONTENT) at command_event.c:963
    #18 0x00005555555fae8e in menu_common_load_content (core_path=core_path@entry=0x0, fullpath=fullpath@entry=0x0, persist=persist@entry=false, type=type@entry=CORE_TYPE_PLAIN)
        at menu/menu.c:168
    #19 0x0000555555630ccf in rarch_defer_core_wrapper (idx=3, entry_idx=0, path=0x7fffffff5520 "Alien vs Predator (USA) (Proto).lnx", hash_label=5381, is_carchive=<optimized out>)
        at menu/cbs/menu_cbs_ok.c:423
    #20 0x0000555555619926 in menu_entry_action (entry=entry@entry=0x7fffffff5520, i=<optimized out>, action=action@entry=MENU_ACTION_OK) at menu/menu_entry.c:381
    #21 0x0000555555648888 in generic_menu_iterate (action=MENU_ACTION_OK) at menu/drivers/menu_generic.c:290
    #22 0x0000555555585734 in rarch_main_iterate (sleep_ms=0x7fffffffe6bc) at runloop.c:1060
    #23 0x000055555557b817 in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:330
    #24 0x00007ffff0a35610 in __libc_start_main () from /usr/lib/libc.so.6
    #25 0x00005555555781d9 in _start ()

**Comment by bspruck** [comment]
What do you mean by "no intro roms"? Can you please give an example?

**Comment by hizzlekizzle** [comment]
From the No-Intro release group. I think the issue is that they've switched to headerless ROMs for their sets and Handy requires those headers to know how to load them.

**Comment by bspruck** [comment]
Am 10.01.2016 um 19:43 schrieb hizzlekizzle:
>
> From the No-Intro release group. I think the issue is that they've
> switched to headerless ROMs for their sets and Handy requires those
> headers to know how to load them.
>
>
Nothing related to the lynx emulation than?

**Comment by hizzlekizzle** [comment]
I don't think so. When people have reported it on the forum, it's always been a header issue. Finding a headered set has always resolved it, AFAIK.

**Comment by Kivutar** [comment]
Definitely not an emulation bug.

I just declared this bug because the database used by RetroArch is based on no-intro DATs. Those DATs contains the CRCs of headerless roms (I think). So when we scan those romset to generate playlists in RetroArch, the playlist will be filled but no rom will launch with handy.

I have no idea of what kind of information is stored in the header of the lynx roms.

One thing is sure, the same kind of problem happens for NES roms, and it's a big issue for Lakka, our linux distribution, that relies a lot on scanning.

We have to either add support for a per core database of external headers, or regenerate our database with checksums of the roms with headers.

**Comment by Oggom** [comment]
@LLeny 
This issue is still valid (see the comments in the pull request).

**Comment by LLeny** [comment]
Refers to the "No-Intro" ROM release group, not homebrew without intro.

**Comment by LLeny** [comment]
@Kivutar Could you please confirm it's corrected after #17 and the latest no-intro ROM ? I tried a few with success.
