### ISSUE TITLE
RoadBlasters - Graphical Glitches

### ISSUE THREAD

**Issue by Oggom** [libretro/libretro-handy#3]
I've tested every game in the No-Intro set and all of them except RoadBlasters appear to work fine.

When you start a race the game shows lots of graphical flickering and glitches.
This also happens in the standalone version of Handy and to lesser extend in Mednafen too.

Since Handy has been abandoned for years chances of seeing it fixed are rather low I suppose.

**Comment by MoochMcGee** [comment]
Is this fixed by #50? If so, can we close this issue please?

**Comment by tryal-star** [comment]
I think it's fixed but I have yet to play the entire game through.

**Comment by hizzlekizzle** [comment]
I'll go ahead and close this, then, and if it's still a problem we can reopen it.
