### ISSUE TITLE
Zaku, Homebrew not working on emulator

### ISSUE THREAD

**Issue by Darknior** [libretro/libretro-handy#36]
Hi

Zaku is an excellent Homebrew made on Lynx and it not working fine on Handy.
I have try it on Raspberry PI 3, with Retropie.
When i launch the game i can see a loading image, and after "Black Screen" !
Is some one here can try it to found the bug please ?
Here is the forum where we speak about this game.
Thanks

http://www.emuxtras.net/forum/viewtopic.php?f=222&t=6246&sid=4cc451c99288035b8067ce8c10d20a2f

**Comment by LLeny** [comment]
I believe it's a not a bug but a feature introduced by the author of Zaku who is still selling his work. Very unlikely to be circumvented.

**Comment by Darknior** [comment]
Arf so bad :(
I understand some one must do retro engineering to understand it ...

**Comment by LLeny** [comment]
I think it's more of an ethical thing, the Lynx homebrew community supports the active devs for their work.

**Comment by b-spruck** [comment]
Indeed.
it would require to do some more 
(a) cycle accurate emulation of the asics
(b) undocumented behaviour
And at least I do not see why I should do that.  But this discussion is repeating again and agin in different forums.

**Comment by Darknior** [comment]
Ok thanks, i only ask a question to emulate a cool game. But you do what you want @b-spruck

@LLeny i understand you for sure, but one day this game will stop to be selling ... so bad to not permit users to play with it.
And for information , i don't have any Lynx and i don't want one, i only want to play games on my PI.
Like i don't want a NES, but i play games on PI, i have ask to the author of Twin Dragons to release his game in ROM version, he do it and i buy it to give hi money for his work. I do it for many games because i LOVE HOME BREWS and all gamers are not PIRATE :(
I also pay for some OpenBOR games ... always to help programmers ...

Here i only ask if it will be possible to play a game i will try to buy if possible.
Thanks

**Comment by zakuahem** [comment]
MAME works since 2016 (0.173)
https://wiki.mamedev.org/index.php/MAME_0.173

Game is now dead, no longer being published.
https://atariage.com/forums/topic/151560-zaku-for-the-atari-lynx-official-thread/page/31/

But if you can obtain and dump your own copy.... Turn on / off this hack to get around the WAI stuck loop problem. Rest of game plays but has sound issue.
https://github.com/libretro/libretro-handy/pull/61

**Comment by Darknior** [comment]
@zakuahem WOAW thanks a lot for this hack :) 
I will try it with pleasure if it is merged :)
And you write there is a sound problem, have you some idea to fix it ?
Thanks

**Comment by zakuahem** [comment]
There's this strange metallic buzzing sound that varies in pitch. Unsure if it was in earlier builds too.

So I was wondering why MAME can run it so easily. Turns out it's a Handy + Mednafen only feature. $fd97 returns 0x42 on Handy-type emulators only; not on real hardware or by extension MAME.
```
4205  ad 97 fd  lda $fd97
4208  c9 42     cmp #$42
420a  d0 01     bne $420d
420c  db        stp  ??
420d  a9 01     lda #$01
```

Back then it was a good idea sure. No complaints. With modern emulator competition that focuses on accuracy (MAME et al), this no longer makes sense to use.

**Comment by Darknior** [comment]
Excellent i see your new push :)

> There's this strange metallic buzzing sound that varies in pitch. Unsure if it was in earlier builds too.

Arf ... i don't know :(
Is LR-Handy miss some real Handy update ??
So bad if no one continue to update this excellent core ...

**Comment by zakuahem** [comment]
Could be the other way around too; someone might've taken out something from upstream Handy that damaged the percussion. Tried it in a standalone Handy and it sounds great. I'll dig around with the earlier git commits and research this.

**Comment by Darknior** [comment]
Excellent, thanks a lot, so few people working on some RA cores ...

**Comment by zakuahem** [comment]
Narrowed it to this commit. The Zendocon laughing spider. Which is weird but trying to find a fix that satisfies both games is a mystery so far.
https://github.com/libretro/libretro-handy/commit/434786dac2b23c5ed00c5ddc17a632839f494aba

**Comment by Darknior** [comment]
The only solution if it's the problem will be to add an Audio CORE option.
Like that we can choose when we need it for a game and save it for this game. 
And by default make the set that is the best for most of games.

**Comment by zakuahem** [comment]
This Handy PR fixes sound in both games (Zendocon and Zaku)
https://github.com/libretro/libretro-handy/pull/63

Also tried Beetle Lynx w/ Zaku patch and both games work perfectly there too. Only Roadblasters need fixing, which I'll submit.

**Comment by zakuahem** [comment]
Hopefully you'll find someone to compile the RPI3 core for you (with all the hotfixes).

**Comment by Darknior** [comment]
WOAW excellent you fix them so fast <3
Some will compile it for sure, but PR must be accepted first ... i wish it will not take so many time ...
I wish you will found for Roadblaster too ;)

You are strong, if you have some free time to help on other core with some bugs no one fixing ... I know some of them like Vectrex one ;)

**Comment by zakuahem** [comment]
@Darknior 
Try this RPI build.
https://github.com/zakuahem/libretro-handy/raw/rpi3/handy_libretro.so

**Comment by Darknior** [comment]
@zakuahem Thanks a lot i will try it :)

**Comment by Darknior** [comment]
@zakuahem i've try your .so file and the game Zaku always not working :(
It start, i can see the "Please wait" screen, next a little glish on screen bottom, next black screen and that's all, nothing more :(

**Comment by zakuahem** [comment]
In case I made a mistake, try again here.
https://github.com/zakuahem/libretro-handy/blob/1c5d82a32aaccdc6c591f34219d268b669c94ea0/handy_libretro.so?raw=true

If still fails, report Zaku hash.

**Comment by Darknior** [comment]
WOAW incredible now it works so fine !!! Thanks a lot i love this game, it's so fun :D 
Really if you have some free time; just a little, come help us on the Batocera team please ;)
We have some core to upgrade, and no one with enough free time to do it ... like the Vectrex core for exemple ...
Not updated with the last real emulator source code to make working fine last Homebrews ...
It bug on PI with some sound glitch and impossible to use shader ...  and it's strange because working perfectly on PC.
