### ISSUE TITLE
Handy clears eeprom saving on closing

### ISSUE THREAD

**Issue by nop90** [libretro/libretro-handy#38]
The emulators correctly creates an eeprom savefile when reseting the rom, but closing the content or the emulator, the eeprom file is ovrwrittem with all zeroes.

The problem is in  libretro.cpp.

retro_deinit()  first calls retro_reset() (that saves the eeprom content to file, than clears the eeprom content calling lynx->reset() ), than saves again the eeprom, but now its cleared so the file content is overwritten.

The lynx->SaveEEPROM() call in retro_deinit() should be removed

**Comment by tryal-star** [comment]
I think it's fixed in master? Tried Flappy Bird demo and it correctly saves my high score.
https://whitelynx.fi/shop/

**Comment by hizzlekizzle** [comment]
I guess I'll close this one and OP can reopen it if the issue remains.
