### ISSUE TITLE
Crash from Null Pointer

### ISSUE THREAD

**Issue by jared6502** [libretro/libretro-handy#40]
The Handy core keeps crashing when left idle for a few hours.

RetroArch: 1.7.6
Core (according to the window title bar): Handy 0.97 08cc633
OS: Windows 7 x64

Unfortunately this is the only debugging information I have at the moment:
Unhandled exception at 0x000000006B985B80 (handy_libretro.dll) in retroarch.exe: 0xC0000005: Access violation reading location 0x0000000000000000. occurred

It has, however, been consistent, and seems to just be a matter of time before it happens once loaded and running.

The game that I have been seeing crashes with is Shanghai (USA, Europe), achievements are enabled, and the run-ahead setting is on in RetroArch when loading.

**Comment by tryal-star** [comment]
This bug is still in the core. After about 59 minutes of letting Shanghai run idle during main play, game triggers a hardware reset. I want to look into this later.

**Comment by trioan** [comment]
I'm sure this bug is fixed. Shanghai correctly self-resets without crashing on time over.
