### ISSUE TITLE
 [Feature Request] Core for Wii/Wii U? 

### ISSUE THREAD

**Issue by Cee123** [libretro/libretro-handy#75]
Hi there, just wondering why this core is not available on Retroarch for Wii.

**Comment by CrankySupertoon** [comment]
because no one wants to work on powerpc

**Comment by Cee123** [comment]
Actually yeah, I did try to build the cores for Wii on Linux, but that was the thing that was giving me the biggest issue is I kept getting errors for powerpc.

**Comment by trioan** [comment]
If I can do it, you can too!
https://ci.appveyor.com/project/trioan/libretro-handy/builds/34709308
https://raw.githubusercontent.com/trioan/libretro-handy/wii/appveyor-git.yml

**Comment by Cee123** [comment]
> If I can do it, you can too!
> https://ci.appveyor.com/project/trioan/libretro-handy/builds/34709308
> https://raw.githubusercontent.com/trioan/libretro-handy/wii/appveyor-git.yml

Nice! I couldn't get it to build just kept getting a bunch of error messages i dont know why.

**Comment by Cee123** [comment]
I tried following these instructions
https://docs.libretro.com/development/retroarch/compilation/wii/

But seems to be something missing here.

**Comment by trioan** [comment]
```
https://docs.libretro.com/development/retroarch/compilation/wii/

You need the homebrew Nintendo Wii SDK libogc and Devkitpro PPC toolchain installed.
```

1) Be sure to use the libretro Devkitpro tools. And manually setup the `DEVKITPPC` and `DEVKITPRO` paths.
https://github.com/libretro/libretro-toolchains/blob/master/wiiu.tar.xz?raw=true

Which I did in my script
```
export DIR = $PWD

export PATH="$DIR/tools/devkitpro/devkitPPC/powerpc-eabi:$PATH"
export DEVKITPPC="$DIR/tools/devkitpro/devkitPPC"
export DEVKITPRO="$DIR/tools/devkitpro"
```

2) Then try ```make -f Makefile platform=wii```

**Comment by Cee123** [comment]
Alright, that's fantastic. Thank you! I'll try and do what you said and see if I can compile it for the Wii. That was what I was missing I think.

**Comment by Cee123** [comment]
@trioan Thanks! That seemed to work.

**Comment by Cee123** [comment]
Nope, it seems like it build everything but there's nothing in the directory. I set the paths for devkitpro. I have it in my /opt/ folder instead of /tools/ so I have it set out like this in my .bashrc file.

export DIR = $PWD

export PATH="$DIR/opt/devkitpro/devkitPPC/powerpc-eabi:$PATH"
export DEVKITPPC="$DIR/opt/devkitpro/devkitPPC"
export DEVKITPRO="$DIR/opt/devkitpro"

But it STILL won't check there. I'm still getting the error /bin/powerpc-eabi-g++: not found.

**Comment by Cee123** [comment]
I copied your script above, and extracted the necessary files, and I'm also now using that same path and everything seems to be working now but still with some minor issues that I'm trying to figure out.

**Comment by trioan** [comment]
Huh. Could be linux path thing. My entire bash script is
```
      cd .
      export DIR=$PWD


      export PATH="$DIR/tools/devkitpro/devkitPPC/powerpc-eabi:$PATH"
      export DEVKITPPC="$DIR/tools/devkitpro/devkitPPC"
      export DEVKITPRO="$DIR/tools/devkitpro"

      git clone https://github.com/libretro/RetroArch Retroarch

      wget "https://github.com/libretro/libretro-toolchains/blob/master/wiiu.tar.xz?raw=true" -O "wiiu.tar.xz"
      mkdir tools
      tar xf wiiu.tar.xz -C tools


      cd $DIR
      make -f Makefile platform=wii
      cp *.a $DIR/Retroarch/dist-scripts

      cd $DIR/Retroarch/dist-scripts
      chmod a+x dist-cores.sh
      ./dist-cores.sh wii
```

**Comment by Cee123** [comment]
I finally got it to compile (and quite a few other cores) by placing the devkitpro files in the root of the drive and merging them with the system files. Now I don't have to worry about paths. I'm using a virtual machine anyway.

So, this core works on the Wii! Runs better than the Mednafen Lynx core... BUT there's a small issue. It doesn't seem to detect the Wii controllers. You can access the Retroarch menu and everything, but the controllers themselves in game don't seem to respond. Not sure why that is. Strange.

**Comment by trioan** [comment]
Beetle Lynx input works?

**Comment by Cee123** [comment]
> Beetle Lynx input works?

Yeah Beetle Lynx works. They've included it in retroarch wii. Works pretty good.

**Comment by Cee123** [comment]
The control problem was also on these other cores I've tried:
- Prosystem
- XRick

So that must be why they dont include these cores in official retroarch wii.

**Comment by trioan** [comment]
First guess: MSB flip.

https://github.com/libretro/libretro-handy/blob/master/libretro/libretro.cpp#L292
```
static unsigned get_lynx_input(void)
{
   unsigned i, res = 0;
   for (i = 0; i < sizeof(btn_map_no_rot) / sizeof(map); ++i)
      res |= input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, btn_map[i].retro) ? btn_map[i].lynx : 0;

#ifdef MSB_FIRST
   return ((res<<8)&0xff00) | ((res>>8)&0xff);
#else
   return res;
#endif
}
```

**Comment by Cee123** [comment]
Well, I'm thinking it might not be to do with those cores now. It's happening with most of my other cores now and seems to be with the latest version/s of retroarch. It's even happening with the cores and retroarch that I've grabbed from a nightly a couple months back. It doesn't matter if I've compiled the cores of got them from a nightly. Some are working, some aren't and it seems to be totally random which cores have working controls. The controls for Cave Story aren't working, neither with Mr Boom and also for FCEUmm. I've tried deleting the retroarch configs and letting it generate new ones. Nothing's working. Really strange.

**Comment by trioan** [comment]
Tried current handy core with Dolphin Wii emulator and input works using virtual GCPad controller.

**Comment by trioan** [comment]
@Cee123 
Do any other Mednafen cores work besides Lynx? Trying to wonder if the Handy core needs to use the updated Libretro input bitmask api.

**Comment by Cee123** [comment]
@trioan Hey yeah well, the controls don't seem to be responding on Mednafen PCE Fast or Mednafen VB at the moment either.

But they are working fine on Mednafen Supergrafx.

https://github.com/libretro/RetroArch/issues/11217

**Comment by trioan** [comment]
Added support for input bitmasks.
https://github.com/libretro/libretro-handy/pull/81


Based on the other working repos, it could fix your Wii input problem. Please test.
https://ci.appveyor.com/project/trioan/libretro-handy/builds/35059824/artifacts

**Comment by trioan** [comment]
@Cee123 
If you have some time, would you mind testing this Wii build to see if your input problems get fixed?
https://ci.appveyor.com/project/trioan/libretro-handy/builds/35169071/artifacts


Based on your working Wii repos, they all use input bitmasks which reads the controller in 1 go. So I think it may cure the Handy problem. If it works, then I guess I'll add it to some of the other bad cores.

**Comment by Cee123** [comment]
@trioan Oh great! Thank you. That's excellent. Yeah i will gladly test it out, see if the issue is fixed with the input bitmask. If that is the issue then it should be a pretty simple fix (hopefully!).

**Comment by Cee123** [comment]
@trioan Well, I just tried it out. And I can say it's working. Good work, you fixed it! That's fantastic, the controls are working fine now!

**Comment by Cee123** [comment]
Yeah that version you posted works perfect.

**Comment by trioan** [comment]
The next problem is that the buildbot is not building this core for Wii?

**Comment by Cee123** [comment]
> 
> 
> The next problem is that the buildbot is not building this core for Wii?

Ah really? Damn, wonder why.

**Comment by trioan** [comment]
Once that gets merged, buildbot will take care of the rest and this ticket can get shut down.

**Comment by twinaphex** [comment]
Should be added now for Wii/WiiU as well as Gamecube.

**Comment by Cee123** [comment]
> Should be added now for Wii/WiiU as well as Gamecube.

Yeah, was added a while ago now. Meant to close this earlier but forgot about it.
