### ISSUE TITLE
Lynx in RetroPie 3.0 Beta 2

### ISSUE THREAD

**Issue by craigerskine** [libretro/libretro-handy#8]
I posted this over in the RetroPie area as I'm not sure if it's a RP issue or a Handy issue. Basically, .rtc and .srm files get created in the roms folder after you launch a game for the first time. Those files prevent the game from loading a second time.

I fixed the issue by changing permissions on the roms folder to prevent writing. Since making that change to my setup I've been able to play all games normally more than one time.

Sorry if this is the wrong place to post this, I'm not sure where the correct place would be as the RP area produced no responses.

https://github.com/petrockblog/RetroPie-Setup/issues/823

![files](https://cloud.githubusercontent.com/assets/56437/7799547/0959e042-02cd-11e5-86ee-37255af7b7ea.png)

![fix](https://cloud.githubusercontent.com/assets/56437/7799549/0ce6ab32-02cd-11e5-985b-06813e43047b.png)

**Comment by hizzlekizzle** [comment]
Confirmed. It looks like it's writing that stuff to a temporary file for serialization purposes and then it's not cleaning up after itself properly when you quit and is instead dumping it into the save directory (content directory by default).
