### ISSUE TITLE
No video output since d10b506003d33bed7be5a7477dad634caae9b749

### ISSUE THREAD

**Issue by joolswills** [libretro/libretro-handy#9]
Getting just background colour output and music etc. This is running on retroarch on a Raspberry Pi.

bisected to

d10b506003d33bed7be5a7477dad634caae9b749 is the first bad commit

```
commit d10b506003d33bed7be5a7477dad634caae9b749
Author: twinaphex <libretro@gmail.com>
Date:   Fri Jul 17 02:39:28 2015 +0200

    Cleanups/warning fixes
```

reverting that commit fixes it.

**Comment by joolswills** [comment]
Also the patch above introduces wrong line indentation into the code (the code uses tabs, but the changes in d10b506 use spaces). The problem is in lynx/Susie.cpp
 - going through it now.

**Comment by joolswills** [comment]
Aah moving the return 0 in the switch is not correct - as it will cause 0 to be returned for other cases when they should just continue

**Comment by twinaphex** [comment]
There's nothing 'wrong' about that line indentation though, it's the way I prefer it.

**Comment by joolswills** [comment]
No offence, but the original file is tab indentation. it should be one or the other - on my editor those edits were not indented enough compared to the tabs. If you want to convert the project to spaces (I prefer them), fine but adding two space indented files to a tab indented source could not be argued as correct.

**Comment by joolswills** [comment]
s/files/lines

**Comment by joolswills** [comment]
To be honest, saying "thanks" would be more appropriate - after your patch, it was obviously not tested. but no worries.

**Comment by twinaphex** [comment]
I use three-space indentation for repos, period. I don't care about tab indentation. This is final and not subject to debate.

The patch was not tested indeed. Merging your PR is my way of saying 'thanks'. I don't think any further kind of 'thanking' is required other than that.

**Comment by joolswills** [comment]
If you submit a patch to KDE, Linux, Xorg, or any large project, and your patch does not match their styleguide it would be refused. If you want the whole project to be 3 spaces, convert the files, and good luck later pulling in patches. It's completely obvious not to mix indentation styles - it makes it look a mess. You are a skilled developer, you know this.

Nothing is personal, I just suggested saying thanks is more constructive than getting defensive over indentation. I tend to thank people for fixes on projects I run.

**Comment by twinaphex** [comment]
I have no desire for drama, sorry.  I asked you respectfully before to drop this subject. 

I don't care about what KDE, Linux, Xorg or whatever does.

**Comment by joolswills** [comment]
You keep editing your post - and it gets more and more heated! but ok - good point regarding handy. so convert it then - a good use case to apply your own styleguide, which I will keep to (I already submitted a fix before to an earlier pull request to make it adhere to your styleguide btw). I'm all for consistency.

Thanks for merging my commit.

**Comment by twinaphex** [comment]
I already made a commit earlier that changes everything over to the indentation rules I've set up in Vim, perhaps you missed it, it was maybe around 20 minutes ago.

**Comment by joolswills** [comment]
If it would smooth out things between us, since our other discussion, feel free to remove the posts, and we can leave it as pull request done, and we will all carry on etc (and I will of course continue to feedback stuff). 

Your work on the project is appreciated - of course.

**Comment by bspruck** [comment]
Whats not the conclusion with indentions?
Until now, i dint care about it while submitting patches.
Would make things much easier if there would be a defined style, at best a parameter set for astyle.
